apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8080
  selector:
    io.kompose.service: airflow
status:
  loadBalancer: {}
