apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: flaskapp
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flaskapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-creativa2-hdfs: "true"
        io.kompose.service: flaskapp
    spec:
      containers:
        - env:
            - name: FLASK_ENV
              value: development
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: PROJECT_HOME
              value: /ap
          image: flaskapp
          name: flaskapp
          ports:
            - containerPort: 5010
              hostPort: 5010
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
