apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: hadoop-datanode
  name: hadoop-datanode
spec:
  ports:
    - name: "50075"
      port: 50075
      targetPort: 50075
    - name: "9864"
      port: 9864
      targetPort: 9864
  selector:
    io.kompose.service: hadoop-datanode
status:
  loadBalancer: {}
