apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "8088"
      port: 8088
      targetPort: 8080
  selector:
    io.kompose.service: spark-master
status:
  loadBalancer: {}
