apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-submit
  name: spark-submit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-submit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-creativa2-hdfs: "true"
        io.kompose.service: spark-submit
    spec:
      containers:
        - args:
            - bash
            - -c
            - sleep 20 && /spark/bin/spark-submit  --master spark://spark-master:7077  --packages org.mongodb.spark:mongo-spark-connector_2.12:10.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.1  --class es.upm.dit.ging.predictor.MakePrediction  /app/target/scala-2.12/flight_prediction_2.12-0.1.jar
          env:
            - name: SPARK_MASTER
              value: spark://spark-master:7077
          image: bde2020/spark-submit:3.2.1-hadoop3.2
          name: spark-submit
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: spark-submit-claim0
            - mountPath: /models/models
              name: spark-submit-claim1
      restartPolicy: Always
      volumes:
        - name: spark-submit-claim0
          persistentVolumeClaim:
            claimName: spark-submit-claim0
        - name: spark-submit-claim1
          persistentVolumeClaim:
            claimName: spark-submit-claim1
status: {}
