apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-creativa2-hdfs: "true"
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: INIT_DAEMON_STEP
              value: setup_spark
          image: bde2020/spark-master:3.2.1-hadoop3.2
          name: spark-master
          ports:
            - containerPort: 7077
              hostPort: 7077
              protocol: TCP
            - containerPort: 8080
              hostPort: 8088
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /models/models
              name: spark-master-claim0
      restartPolicy: Always
      volumes:
        - name: spark-master-claim0
          persistentVolumeClaim:
            claimName: spark-master-claim0
status: {}
